/**
 * TypeScript declaration file for Next.js.
 * This file is automatically generated and should not be edited manually.
 */

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
