version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    # Removing volume here so the '.next' build folder won't be overwritten
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
