name: EKS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: eks
          eks-region: us-east-1
          eks-cluster-name: notes-eks

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/backend-configmap.yaml
          kubectl apply -f kubernetes/backend-secret.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml
          kubectl apply -f kubernetes/ingress.yaml
          kubectl apply -f kubernetes/backend-hpa.yaml
