apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
  namespace: notes-app
  labels:
    app: notes-backend
spec:
  selector:
    app: notes-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
