apiVersion: v1
kind: Secret
metadata:
  name: notes-backend-secret
  namespace: notes-app
type: Opaque
data:
  # Example: echo -n 'supersecretkey' | base64
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk=
  # If you had a DB password, you'd store it here:
  # DB_PASSWORD: BASE64_ENCODED_PASSWORD
