# EKS cluster configuration file for eksctl.
# Specifies the cluster name, region, and node group settings.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: notes-eks
  region: us-east-1
  version: "1.27"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: notes-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    volumeSize: 20
    privateNetworking: true
    labels:
      role: notes-workers
    tags:
      nodegroup-role: notes
    ssh:
      allow: true
      publicKeyName: "my-keypair"
