apiVersion: v1
kind: Service
metadata:
  name: notes-frontend-service
  namespace: notes-app
  labels:
    app: notes-frontend
spec:
  selector:
    app: notes-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
