apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend-deployment
  namespace: notes-app
  labels:
    app: notes-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
      - name: notes-frontend-container
        image: YOUR_FRONTEND_IMAGE_HERE
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
      imagePullSecrets:
        - name: aws-ecr-credentials
